# Homepage
learn_lingua:
    resource: "@MatteoLearnBundle/Resources/config/routing.yml"
    prefix:   /
    
# Sonata Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
# Login for Sonata Admin
login:
    pattern:   /login
    defaults:  { _controller: MatteoLearnBundle:Main:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
